# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='datavalue',
            field=models.FloatField(default='SHOP', max_length=255, verbose_name='shop'),
        ),
    ]
