# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-13 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20170224_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='NAME', max_length=255, verbose_name='username')),
                ('starttime', models.IntegerField(default=0, verbose_name='starttime')),
                ('finishtime', models.IntegerField(default=0, verbose_name='finishtime')),
                ('hint_action1_1', models.BooleanField(default=False, verbose_name='hint1_1')),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='datavalue',
            field=models.CharField(default='SHOP', max_length=255, verbose_name='shop'),
        ),
    ]
