# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-15 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20170313_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beacon_id', models.IntegerField(default=0, verbose_name='beacon')),
                ('uuid', models.IntegerField(default=0, verbose_name='uuid')),
                ('major', models.IntegerField(default=0, verbose_name='major')),
                ('minor', models.IntegerField(default=0, verbose_name='minor')),
                ('category', models.CharField(default='CATEGORY', max_length=255, verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_num', models.IntegerField(default=0, verbose_name='hint_number')),
                ('hint_sent', models.CharField(default='HINT', max_length=255, verbose_name='hint_sentence')),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(default='SHOPNAME', max_length=255, verbose_name='shopname')),
                ('shop_id', models.IntegerField(default=0, verbose_name='shop_id')),
                ('beacon', models.IntegerField(default=0, verbose_name='beacon')),
            ],
        ),
        migrations.CreateModel(
            name='Treasure_Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treasure', models.IntegerField(default=0, verbose_name='treasure')),
                ('beacon', models.IntegerField(default=0, verbose_name='beacon')),
            ],
        ),
        migrations.CreateModel(
            name='UsedHint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='NAME', max_length=255, verbose_name='username')),
                ('treasure1_1', models.IntegerField(default=0, verbose_name='1_1time')),
                ('treasure1_2', models.IntegerField(default=0, verbose_name='1_2time')),
                ('treasure1_3', models.IntegerField(default=0, verbose_name='1_3time')),
                ('treasure2_1', models.IntegerField(default=0, verbose_name='2_1time')),
                ('treasure2_2', models.IntegerField(default=0, verbose_name='2_2time')),
                ('treasure2_3', models.IntegerField(default=0, verbose_name='2_3time')),
                ('treasure3_1', models.IntegerField(default=0, verbose_name='3_1time')),
                ('treasure3_2', models.IntegerField(default=0, verbose_name='3_2time')),
                ('treasure3_3', models.IntegerField(default=0, verbose_name='3_3time')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='shopname',
            field=models.CharField(default='SHOP', max_length=255, verbose_name='shopname'),
        ),
        migrations.AddField(
            model_name='user',
            name='treasure1',
            field=models.IntegerField(default=0, verbose_name='treasure1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hint_action1_1',
            field=models.IntegerField(default=0, verbose_name='hint1_1'),
        ),
    ]
